import { Footer } from "@/modules/Footer";
import { Header } from "@/modules/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactQueryClientProvider } from "./ReactQuery";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ReactQueryClientProvider>
					<div
						className='relative min-h-screen bg-cover bg-center bg-no-repeat fixed-bg'
						style={{ backgroundImage: `url('/bg/bg_anime.gif')` }}
					>
						<div className='absolute inset-0 bg-pink-500 opacity-30 blur-3xl'></div>
						<div className='relative z-10'>
							<Header />
							{children}
							<Footer />
						</div>
					</div>
				</ReactQueryClientProvider>
			</body>
		</html>
	);
}
